USE `ps3`;

INSERT INTO `publisher` VALUES(1,'microsoft');
INSERT INTO `publisher` VALUES(2,'meta');
INSERT INTO `publisher` VALUES(3,'amazon');
INSERT INTO `publisher` VALUES(4,'mit press');
INSERT INTO `publisher` VALUES(5,'harvard art school');
INSERT INTO `publisher` VALUES(6,'mit law school');

INSERT INTO `editor` VALUES(1,1,'cran','berry');
INSERT INTO `editor` VALUES(2,1,'blue','berry');
INSERT INTO `editor` VALUES(3,2,'black','berry');
INSERT INTO `editor` VALUES(4,3,'rasp','berry');
INSERT INTO `editor` VALUES(5,4,'berry','berry');
INSERT INTO `editor` VALUES(6,5,'no','berry');
INSERT INTO `editor` VALUES(7,6,'apple','ipad');

INSERT INTO `author` VALUES(1,'apple','bee');
INSERT INTO `author` VALUES(2,'time','square');
INSERT INTO `author` VALUES(3,'golf','ball');
INSERT INTO `author` VALUES(4,'happy','bee');
INSERT INTO `author` VALUES(5,'new','year');
INSERT INTO `author` VALUES(6,'apple','square');
INSERT INTO `author` VALUES(7,'golf','bee');
INSERT INTO `author` VALUES(8,'time','ball');
INSERT INTO `author` VALUES(9,'apple','bee');

INSERT INTO `customer` VALUES(1,'one','cus');
INSERT INTO `customer` VALUES(2,'two','cus');
INSERT INTO `customer` VALUES(3,'three','customer');

INSERT INTO `order` VALUES(1,1,'2021-03-25');
INSERT INTO `order` VALUES(2,1,'2022-03-25');
INSERT INTO `order` VALUES(3,2,'2022-04-25');
INSERT INTO `order` VALUES(4,2,'2022-01-25');
INSERT INTO `order` VALUES(5,2,'2023-06-25');
INSERT INTO `order` VALUES(6,2,'2012-01-15');
INSERT INTO `order` VALUES(7,2,'2000-12-25');
INSERT INTO `order` VALUES(8,3,'1950-11-11');

INSERT INTO `book` VALUES(1,4,'1.001','gpa');
INSERT INTO `book` VALUES(2,4,'1.125','gpa');
INSERT INTO `book` VALUES(3,5,'1.001','solution');
INSERT INTO `book` VALUES(4,5,'1.125','gpa');
INSERT INTO `book` VALUES(5,6,'linear algebra','tl;dr');
INSERT INTO `book` VALUES(6,1,'elder rings','game');
INSERT INTO `book` VALUES(7,1,'dark souls 3','game');
INSERT INTO `book` VALUES(8,2,'ps1','antique');
INSERT INTO `book` VALUES(9,2,'ps2','fifa');
INSERT INTO `book` VALUES(10,2,'ps3','junk');
INSERT INTO `book` VALUES(11,3,'ps4','winner');
INSERT INTO `book` VALUES(12,1,'xbox','green');

INSERT INTO `junction_editor_book` VALUES(1,1);
INSERT INTO `junction_editor_book` VALUES(2,1);
INSERT INTO `junction_editor_book` VALUES(3,2);
INSERT INTO `junction_editor_book` VALUES(4,3);
INSERT INTO `junction_editor_book` VALUES(5,4);
INSERT INTO `junction_editor_book` VALUES(6,5);
INSERT INTO `junction_editor_book` VALUES(7,6);
INSERT INTO `junction_editor_book` VALUES(1,6);
INSERT INTO `junction_editor_book` VALUES(2,6);
INSERT INTO `junction_editor_book` VALUES(3,7);
INSERT INTO `junction_editor_book` VALUES(4,8);
INSERT INTO `junction_editor_book` VALUES(5,9);
INSERT INTO `junction_editor_book` VALUES(6,10);
INSERT INTO `junction_editor_book` VALUES(7,10);
INSERT INTO `junction_editor_book` VALUES(1,10);
INSERT INTO `junction_editor_book` VALUES(2,11);
INSERT INTO `junction_editor_book` VALUES(3,12);

INSERT INTO `junction_author_book` VALUES(1,1);
INSERT INTO `junction_author_book` VALUES(2,1);
INSERT INTO `junction_author_book` VALUES(3,2);
INSERT INTO `junction_author_book` VALUES(4,3);
INSERT INTO `junction_author_book` VALUES(5,3);
INSERT INTO `junction_author_book` VALUES(6,3);
INSERT INTO `junction_author_book` VALUES(7,4);
INSERT INTO `junction_author_book` VALUES(8,4);
INSERT INTO `junction_author_book` VALUES(9,5);
INSERT INTO `junction_author_book` VALUES(1,6);
INSERT INTO `junction_author_book` VALUES(2,7);
INSERT INTO `junction_author_book` VALUES(3,8);
INSERT INTO `junction_author_book` VALUES(4,9);
INSERT INTO `junction_author_book` VALUES(5,9);
INSERT INTO `junction_author_book` VALUES(6,9);
INSERT INTO `junction_author_book` VALUES(7,10);
INSERT INTO `junction_author_book` VALUES(8,11);
INSERT INTO `junction_author_book` VALUES(9,12);

INSERT INTO `junction_order_book` VALUES(1,12);
INSERT INTO `junction_order_book` VALUES(2,11);
INSERT INTO `junction_order_book` VALUES(3,10);
INSERT INTO `junction_order_book` VALUES(4,9);
INSERT INTO `junction_order_book` VALUES(5,8);
INSERT INTO `junction_order_book` VALUES(6,7);
INSERT INTO `junction_order_book` VALUES(7,6);
INSERT INTO `junction_order_book` VALUES(8,5);
INSERT INTO `junction_order_book` VALUES(8,4);
INSERT INTO `junction_order_book` VALUES(1,3);
INSERT INTO `junction_order_book` VALUES(1,2);
INSERT INTO `junction_order_book` VALUES(1,1);
INSERT INTO `junction_order_book` VALUES(1,6);
INSERT INTO `junction_order_book` VALUES(2,2);
INSERT INTO `junction_order_book` VALUES(3,3);
INSERT INTO `junction_order_book` VALUES(3,4);
INSERT INTO `junction_order_book` VALUES(4,5);
INSERT INTO `junction_order_book` VALUES(5,6);
INSERT INTO `junction_order_book` VALUES(6,12);
INSERT INTO `junction_order_book` VALUES(7,8);
INSERT INTO `junction_order_book` VALUES(8,9);
INSERT INTO `junction_order_book` VALUES(5,10);
INSERT INTO `junction_order_book` VALUES(6,11);
INSERT INTO `junction_order_book` VALUES(2,12);

INSERT INTO `contract` VALUES(1,1,1,4,12345);
INSERT INTO `contract` VALUES(2,1,2,4,6520);
INSERT INTO `contract` VALUES(3,2,3,4,305);
INSERT INTO `contract` VALUES(4,3,4,5,20);
INSERT INTO `contract` VALUES(5,3,5,5,1);
INSERT INTO `contract` VALUES(6,3,6,5,55);
INSERT INTO `contract` VALUES(7,4,7,5,66);
INSERT INTO `contract` VALUES(8,4,8,5,15611);
INSERT INTO `contract` VALUES(9,5,9,6,1000);
INSERT INTO `contract` VALUES(10,6,1,1,200);
INSERT INTO `contract` VALUES(11,7,2,1,70000);
INSERT INTO `contract` VALUES(12,8,3,2,65535);
INSERT INTO `contract` VALUES(13,9,4,2,14285);
INSERT INTO `contract` VALUES(14,9,5,2,2587);
INSERT INTO `contract` VALUES(15,9,6,2,63100);
INSERT INTO `contract` VALUES(16,10,7,2,2);
INSERT INTO `contract` VALUES(17,11,8,3,333);
INSERT INTO `contract` VALUES(18,12,9,1,NULL);
